# Método de Jacobi

In [10]:
using  LinearAlgebra

In [11]:
function Jacobi(A,b,x0=Nothing,iters = 10,tol= 0.01)

   
    D = Diagonal(A)
    L = -(LowerTriangular(A) - D )
    U = -(UpperTriangular(A) - D )
    D1 = inv(D)
    T = D1*(L+U)
    C = D1*b 
    xk = zeros(size(A)[1])

    n_iters = 0

    if x0 != Nothing
        xk = x0
    end

    for i in 1:iters
        new_x = T*xk +C
        if norm(new_x-xk) < tol
            xk = new_x
            n_iters +=1
            break
        end
        xk = new_x
        n_iters +=1
    end
    
    return iters,xk
end


function GaussSeidel(A,b,x0=Nothing,iters = 10,tol= 0.01)
    
    D = Diagonal(A)
    L = -(LowerTriangular(A) - D )
    U = -(UpperTriangular(A) - D )
    DL = inv(D-L)
    T = DL*U
    C = DL*b
    xk = zeros(size(A)[1])

    n_iters = 0

    if x0 != Nothing
        xk = x0
    end

    for i in 1:iters
        new_x = T*xk +C
        if norm(new_x-xk) < tol
            xk = new_x
            n_iters += 1
            break
        end
        xk = new_x
        n_iters +=1
    end
    
    return n_iters,xk
end

GaussSeidel (generic function with 4 methods)

In [12]:
A = [
    10 2 1
    1  5 1
    2  3 10]

b = [7 
    -8 
     6]

3-element Vector{Int64}:
  7
 -8
  6

In [13]:
iters,xj = Jacobi(A,b)
println("iters Jacobi: $iters")
display(xj)

iters,xgs = GaussSeidel(A,b)
println("Iters GaussSeidel: $iters")
display(xgs)


3-element Vector{Float64}:
  1.0002360000000001
 -1.998936
  1.0002840000000002

3-element Vector{Float64}:
  1.0000228008
 -2.00016897456
  1.0000461322080003

iters Jacobi: 10
Iters GaussSeidel: 4


In [89]:
a,b = 0,1
c,d = 0,1

cy(x) = 0
dy(x) = 100*x
ax(y) = 0
bx(y) = 100*y 


f(x,y) = 0

h = 0.25
k = 0.25

nx = Int((b-a)/h)
ny = Int((d-c)/k)

λ = k^2/h^2 

1.0

In [90]:
x = LinRange(a,b,nx+1)
y = LinRange(c,d,ny+1)
display(x)
display(y)

5-element LinRange{Float64, Int64}:
 0.0, 0.25, 0.5, 0.75, 1.0

5-element LinRange{Float64, Int64}:
 0.0, 0.25, 0.5, 0.75, 1.0

In [91]:
U = zeros(nx+1,ny+1)
U[1,1:nx+1] = map(cy,x)
U[ny+1,1:nx+1] = map(dy,x)
U[1:ny+1,1] = map(ax,y)
U[1:ny+1,nx+1] = map(bx,y)
U

5×5 Matrix{Float64}:
 0.0   0.0   0.0   0.0    0.0
 0.0   0.0   0.0   0.0   25.0
 0.0   0.0   0.0   0.0   50.0
 0.0   0.0   0.0   0.0   75.0
 0.0  25.0  50.0  75.0  100.0

In [92]:
A = zeros((nx-1)*(ny-1),(nx-1)*(ny-1))
B = zeros((nx-1)*(ny-1))

9-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [99]:
function get_l(i,j,N)
    return (j-1)*N + i
end

get_l (generic function with 1 method)

In [110]:
A = zeros((nx-1)*(ny-1),(nx-1)*(ny-1))
B = zeros((nx-1)*(ny-1))

for i in 1:3
    for j in 1:3
        v_index = get_l(j,i,3)
        println("($i,$j) = $v_index")
        v_index_left = get_l(j-1,i,nx-1)
        v_index_rigth = get_l(j+1,i,nx-1)
        v_index_bot = get_l(j,i-1,nx-1)
        v_index_top = get_l(j,i+1,nx-1)

        A[v_index,v_index] = 10
        
        if (v_index_left >=1) & (v_index_left <=9)
            A[v_index,v_index_left] = 1
        end

        if (v_index_rigth >=1) & (v_index_rigth <=9)
            A[v_index,v_index_rigth] = 2
        end

        if (v_index_bot >=1) & (v_index_bot <=9)
            A[v_index,v_index_bot] = 3
        end

        if (v_index_top >=1) & (v_index_top <=9)
            A[v_index,v_index_top] = 4
        end
    end
end
A

(1,1) = 1
(1,2) = 2
(1,3) = 3
(2,1) = 4
(2,2) = 5
(2,3) = 6
(3,1) = 7
(3,2) = 8
(3,3) = 9


9×9 Matrix{Float64}:
 10.0   2.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0
  1.0  10.0   2.0   0.0   4.0   0.0   0.0   0.0   0.0
  0.0   1.0  10.0   2.0   0.0   4.0   0.0   0.0   0.0
  3.0   0.0   1.0  10.0   2.0   0.0   4.0   0.0   0.0
  0.0   3.0   0.0   1.0  10.0   2.0   0.0   4.0   0.0
  0.0   0.0   3.0   0.0   1.0  10.0   2.0   0.0   4.0
  0.0   0.0   0.0   3.0   0.0   1.0  10.0   2.0   0.0
  0.0   0.0   0.0   0.0   3.0   0.0   1.0  10.0   2.0
  0.0   0.0   0.0   0.0   0.0   3.0   0.0   1.0  10.0

In [95]:
A = zeros((nx-1)*(ny-1),(nx-1)*(ny-1))
B = zeros((nx-1)*(ny-1))

for i in 1:nx-1
    for j in 1:ny-1
        
        if i==j
            println("i=$i, j=$j")
            v_index = get_l(j,i,nx-1)
            A[i,v_index] = 2
        end
        # v_index_left = get_l(j-1,i,nx-1)
        # v_index_rigth = get_l(j+1,i,nx-1)
        # v_index_bot = get_l(j,i-1,nx-1)
        # v_index_top = get_l(j,i+1,nx-1)

        # println("v_index: $v_index")
        # println("v_index_left: $v_index_left")
        # println("v_index_rigth: $v_index_rigth")
        # println("v_index_bot: $v_index_bot")
        # println("v_index_top: $v_index_top")
    end
end
A

i=1, j=1
i=2, j=2
i=3, j=3


9×9 Matrix{Float64}:
 2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0